name: Build & Release Extension

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      zip-path: ${{ steps.build.outputs.zip-path }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build extension ZIP
        id: build
        run: |
          python generateFiles.py --includeExtended --buildExtension
          echo "zip-path=dist/brokersitehelper.zip" >> $GITHUB_OUTPUT

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: ${{ steps.build.outputs.zip-path }}

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: extension-zip

      - name: Move and flatten ZIP
        run: |
          mv dist/brokersitehelper.zip brokersitehelper.zip
          ls -l brokersitehelper.zip

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: brokersitehelper.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


