name: Build & Release Chrome Extension

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install pillow tabulate requests

      - name: Build extension ZIP
        run: python generateFiles.py --includeExtended --buildExtension

      - name: Check extension ZIP contents
        run: unzip -l dist/brokersitehelper.zip

      - name: Upload built ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/brokersitehelper.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
